---
- name: Configure user account, banner message and static route
  hosts: network_devices
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure user account
      cisco.ios.ios_config:
        lines:
          - username admin privilege 15 secret Admin123!

    - name: Configure banner message
      cisco.ios.ios_banner:
        banner: motd
        text: Unauthorized access is prohibited!
        state: present

    - name: Configure static route
      cisco.ios.ios_config:
        lines:
          - ip route 192.168.20.0 255.255.255.0 192.168.56.1
